/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admintareas;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author David Hurtado
 */
public class AdministradordeTareas extends javax.swing.JFrame {
    
    DefaultTableModel mt;
    String[] enc={"                     Procesos"};
    String[][] datos=null;
   
         
    public AdministradordeTareas() {
       initComponents();
       this.setLocationRelativeTo(null);
       procesos.setFocusable(false);
       mt= new DefaultTableModel(datos,enc);     
       this.jTable2.setModel(mt); 
     }
    public static List listRunningProcesses() {
List<String> processes = new ArrayList<String>();
try {
String line;
Process p = Runtime.getRuntime().exec("tasklist.exe /nh");
BufferedReader input = new BufferedReader
(new InputStreamReader(p.getInputStream()));
while ((line = input.readLine()) != null) {
if (!line.trim().equals("")) {

processes.add(line.substring(0, line.indexOf(" ")));
    }

}
input.close();
    }
        catch (Exception err) {
        err.printStackTrace();
}
        return processes;
}
    void LimpiarTabla(){
        int a =mt.getRowCount()-1;  //Índices van de 0 a n-1
            for(int i=a;i>=0;i--){  
            mt.removeRow(i);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonTask2 = new org.edisoncor.gui.button.ButtonTask();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        procesos = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jTable2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "PROCESOS"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 197, 382));

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel1.setText("ADMINISTRADOR DE TAREAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 38));

        buttonTask2.setBackground(new java.awt.Color(0, 0, 0));
        buttonTask2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/check.fw.png"))); // NOI18N
        buttonTask2.setText(" ");
        buttonTask2.setCategorySmallFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        buttonTask2.setDescription("MOSTRAR PROCESOS");
        buttonTask2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTask2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 275, 59));

        labelMetric1.setBackground(new java.awt.Color(0, 255, 204));
        labelMetric1.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric1.setText("NUM. DE PROCESOS");
        labelMetric1.setColorDeSombra(new java.awt.Color(0, 204, 204));
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(labelMetric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        procesos.setForeground(new java.awt.Color(102, 0, 51));
        procesos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        procesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procesosMouseClicked(evt);
            }
        });
        getContentPane().add(procesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 108, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procesosMouseClicked

    }//GEN-LAST:event_procesosMouseClicked

    private void buttonTask2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTask2ActionPerformed
        LimpiarTabla();
        List<String> processes = listRunningProcesses();
        String result = "";
        Iterator<String> it = processes.iterator();
        int i = 0;
        this.procesos.setText(String.valueOf(processes.size()));
        while (it.hasNext()) {
            result += it.next();
            i++;
            if (i==1) {
                Object[] s={result};
                mt.addRow(s);
                result="";
                i = 0;
            }
        }
    }//GEN-LAST:event_buttonTask2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradordeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradordeTareas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask buttonTask2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.textField.TextFieldRound procesos;
    // End of variables declaration//GEN-END:variables
}
